### PR TITLE
Enabling TLS by default

### PR DESCRIPTION
**Pull request by tlisonbee**

### CODE REVIEW

**Comment by fieldju** [comment]
Will this require changes to the the Gateway to enable SSL?

**Comment by sdford** [comment]
@fieldju From what I understand, this won't require updating the gateway, but it will require updating the CMS ELB listener.

Correct me if I'm wrong @tlisonbee

**Comment by tlisonbee** [comment]
Yes, it will require a change to the CMS ELB and probably a manual step or two if you want zero downtime during the upgrade.

**Comment by tlisonbee** [comment]
Merging into highlander branch instead of master

**Pull request closed without merging**
